/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Santé et configuration
         * @description Ne dépend pas de `get_service` : doit répondre **même** si la config est cassée.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Arcs existants dans le JSON de contexte */
        get: operations["list_arcs_api_v1_arcs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fichiers du dossier de métadonnées (vestige V1, facultatif) */
        get: operations["list_metadata_files_api_v1_metadata_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata-files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contenu d'un fichier de métadonnées
         * @description Renvoie le contenu JSON d'un fichier du dossier de métadonnées.
         *
         *     Le nom est **vérifié par appartenance** à la liste réelle du dossier, jamais
         *     concaténé tel quel au chemin : une valeur comme `../../etc/passwd` ne
         *     correspond à aucune entrée de la liste et sort en 404. C'est plus solide
         *     qu'un filtrage de caractères, qui se contourne toujours.
         */
        get: operations["read_metadata_file_api_v1_metadata_files__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calendrier tamrielien complet (données statiques)
         * @description Renvoie tout le calendrier en un appel : le client calcule localement.
         *
         *     Remplace les deux allers-retours HTMX `/suggest-date` et `/date-days`.
         */
        get: operations["get_calendar_api_v1_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Date proposée par défaut pour une catégorie
         * @description Dernière date connue du XML de la catégorie, décomposée en composants.
         */
        get: operations["suggest_date_api_v1_calendar_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/injections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historique filtré */
        get: operations["list_injections_api_v1_injections_get"];
        put?: never;
        /**
         * Exécute le pipeline d'injection JSON -> XML -> PDF
         * @description Lance une injection.
         *
         *     Le corps de réponse a la **même forme** dans les trois cas (succès, doublon,
         *     échec) : seul le code de statut change. Le journal d'exécution est toujours
         *     présent, car c'est lui qui explique ce qui s'est passé.
         */
        post: operations["create_injection_api_v1_injections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/injections/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Valeurs disponibles pour les filtres */
        get: operations["injection_facets_api_v1_injections_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/injections/{injection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Injection */
        get: operations["get_injection_api_v1_injections__injection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/injections/{injection_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Télécharge le PDF archivé */
        get: operations["download_pdf_api_v1_injections__injection_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keymap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * État complet de la carte des touches
         * @description Disposition, familles, assignations et compteurs — en un seul appel.
         *
         *     Le client dispose ainsi de tout l'état : filtrer par famille, chercher une
         *     action ou ouvrir l'éditeur d'une touche ne demande plus d'aller-retour serveur.
         */
        get: operations["get_keymap_api_v1_keymap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keybinds/{scan_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Assigne (ou réassigne) une touche
         * @description Une famille inconnue est refusée plutôt qu'écrite en base.
         *
         *     L'ancienne route l'ignorait silencieusement : le formulaire semblait accepté
         *     mais rien n'était enregistré.
         */
        put: operations["set_keybind_api_v1_keybinds__scan_code__put"];
        post?: never;
        /**
         * Libère une touche
         * @description Idempotent : libérer une touche déjà libre n'est pas une erreur.
         */
        delete: operations["clear_keybind_api_v1_keybinds__scan_code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keybinds/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exporte la carte complète en JSON */
        get: operations["export_keybinds_api_v1_keybinds_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Configuration courante et résultat de sa validation
         * @description Renvoie la configuration **effective**.
         *
         *     C'est-à-dire les variables d'environnement (injectées par `env_file:` en
         *     conteneur) complétées par le fichier éditable — l'ordre de priorité que
         *     `EnvLoader` applique réellement.
         */
        get: operations["get_settings_api_v1_settings_get"];
        /**
         * Écrit la configuration et renvoie sa validation
         * @description Écrit dans le fichier désigné par `CONFIG_ENV_PATH`.
         *
         *     Seules les clés déclarées dans `env_file.FIELDS` sont écrites : une requête ne
         *     peut pas injecter une variable arbitraire dans la configuration.
         */
        put: operations["update_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CalendarOut
         * @description Toutes les données nécessaires pour construire le sélecteur de date.
         */
        CalendarOut: {
            /** Eras */
            eras: number[];
            /** Months */
            months: components["schemas"]["Month"][];
            /** Weekdays */
            weekdays: string[];
            default: components["schemas"]["GameDate"];
        };
        /**
         * Category
         * @description Catégorie d'injection et le fichier XML TakeNotes qu'elle vise.
         */
        Category: {
            /**
             * Key
             * @description Clé technique, ex. « journal »
             */
            key: string;
            /**
             * Xml File
             * @description Fichier d'export TakeNotes correspondant
             */
            xml_file: string;
        };
        /**
         * ConfigStatusOut
         * @description État de santé de l'application et de sa configuration.
         */
        ConfigStatusOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unconfigured";
            /** Config Ok */
            config_ok: boolean;
            /**
             * Problems
             * @default []
             */
            problems: string[];
        };
        /**
         * GameDate
         * @description Date de session décomposée en composants.
         */
        GameDate: {
            /** Era */
            era: number;
            /** Year */
            year: number;
            /** Month Index */
            month_index: number;
            /** Day */
            day: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InjectionCreate
         * @description Corps de `POST /api/v1/injections`.
         *
         *     Le résumé et le texte sont deux champs distincts : le découpage par balises
         *     `Resume :` / `Text :` appartenait au CLI, retiré lors de ce refactor.
         */
        InjectionCreate: {
            /** Category */
            category: string;
            /**
             * Text
             * @description Corps du journal enrichi (requis)
             */
            text: string;
            /**
             * Resume
             * @default
             */
            resume: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Arc
             * @description Arc cible. Vide ou absent -> nouvel arc auto-numéroté.
             */
            arc?: string | null;
            /** @description Date de session. Absente -> dernière date connue de la catégorie. */
            entry_date?: components["schemas"]["GameDate"] | null;
            /**
             * Max Tokens
             * @description Largeur de segmentation XML. Absent -> env.
             */
            max_tokens?: number | null;
            /**
             * Generate Pdf
             * @default true
             */
            generate_pdf: boolean;
            /**
             * Allow Duplicate
             * @description Force l'injection malgré une empreinte de texte déjà connue.
             * @default false
             */
            allow_duplicate: boolean;
        };
        /**
         * InjectionDetail
         * @description Détail complet d'une injection archivée.
         */
        InjectionDetail: {
            /** Id */
            id: number;
            /** Date Injection */
            date_injection: string;
            /** Categorie */
            categorie?: string | null;
            /** Arc */
            arc?: string | null;
            /** Entry Number */
            entry_number?: number | null;
            /** Date Session */
            date_session?: string | null;
            /** Resume */
            resume?: string | null;
            /** Xml File */
            xml_file?: string | null;
            /**
             * Has Pdf
             * @default false
             */
            has_pdf: boolean;
            /** Texte */
            texte?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Pdf Path */
            pdf_path?: string | null;
        };
        /**
         * InjectionFacets
         * @description Valeurs disponibles pour les filtres de l'historique.
         */
        InjectionFacets: {
            /** Categories */
            categories: string[];
            /** Arcs */
            arcs: string[];
        };
        /**
         * InjectionPage
         * @description Page d'historique filtrée.
         */
        InjectionPage: {
            /** Items */
            items: components["schemas"]["InjectionSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * InjectionResultOut
         * @description Résultat d'une injection — renvoyé aussi bien en `201` qu'en `409`/`422`.
         *
         *     Le journal d'exécution est toujours présent : c'est lui qui explique *pourquoi*
         *     une injection a échoué, et il vaut autant en cas d'erreur qu'en cas de succès.
         */
        InjectionResultOut: {
            /** Success */
            success: boolean;
            /** Messages */
            messages: components["schemas"]["LogMessage"][];
            /** Entry Number */
            entry_number?: number | null;
            /** Arc */
            arc?: string | null;
            /** Category */
            category?: string | null;
            /** Xml File */
            xml_file?: string | null;
            /** Injection Id */
            injection_id?: number | null;
            /**
             * Has Pdf
             * @default false
             */
            has_pdf: boolean;
            duplicate?: components["schemas"]["InjectionSummary"] | null;
        };
        /**
         * InjectionSummary
         * @description Ligne d'historique — assez pour un tableau, sans le corps du texte.
         */
        InjectionSummary: {
            /** Id */
            id: number;
            /** Date Injection */
            date_injection: string;
            /** Categorie */
            categorie?: string | null;
            /** Arc */
            arc?: string | null;
            /** Entry Number */
            entry_number?: number | null;
            /** Date Session */
            date_session?: string | null;
            /** Resume */
            resume?: string | null;
            /** Xml File */
            xml_file?: string | null;
            /**
             * Has Pdf
             * @default false
             */
            has_pdf: boolean;
        };
        /**
         * Key
         * @description Une touche physique de la disposition.
         */
        Key: {
            /**
             * Code
             * @description Scan code DirectInput (positionnel, pas la lettre)
             */
            code: number;
            /** Legend */
            legend: string;
            /**
             * Width
             * @description Largeur en unités de keycap
             * @default 1
             */
            width: number;
            /**
             * Height
             * @description Hauteur en unités de keycap (« + » et Entrée du pavé numérique)
             * @default 1
             */
            height: number;
        };
        /**
         * KeyBind
         * @description Assignation d'une touche.
         */
        KeyBind: {
            /** Scan Code */
            scan_code: number;
            /** Action */
            action: string;
            /** Cat */
            cat: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * KeyBindWrite
         * @description Corps de `PUT /api/v1/keybinds/{scan_code}`.
         */
        KeyBindWrite: {
            /** Action */
            action: string;
            /** Cat */
            cat: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * KeyCategory
         * @description Famille de touches : libellé et triplet de couleurs.
         *
         *     Les couleurs viennent de `keyboard_layout.CATEGORIES` et remontent jusqu'aux
         *     variables CSS du keycap. Ajouter une famille reste une modification d'un seul
         *     fichier côté serveur : ni l'API ni le style n'en connaissent la liste.
         */
        KeyCategory: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Ink
             * @description Couleur du texte
             */
            ink: string;
            /**
             * Edge
             * @description Couleur du contour et de la bordure basse
             */
            edge: string;
            /**
             * Face
             * @description Couleur de fond
             */
            face: string;
        };
        /** KeyboardLayoutOut */
        KeyboardLayoutOut: {
            /** Rows */
            rows: components["schemas"]["Key"][][];
            /**
             * Navigation
             * @description Bloc Inser/Suppr/Début/Fin/pages et flèches directionnelles
             */
            navigation: components["schemas"]["Key"][][];
            /** Numpad */
            numpad: components["schemas"]["Key"][][];
            /** Mouse Buttons */
            mouse_buttons: components["schemas"]["Key"][];
            /** Mouse Side */
            mouse_side: components["schemas"]["Key"][];
        };
        /**
         * KeymapOut
         * @description État complet de la carte des touches.
         */
        KeymapOut: {
            layout: components["schemas"]["KeyboardLayoutOut"];
            /** Categories */
            categories: components["schemas"]["KeyCategory"][];
            free_key: components["schemas"]["KeyCategory"];
            /** Binds */
            binds: components["schemas"]["KeyBind"][];
            /**
             * Counts
             * @description Nombre de touches par famille
             */
            counts: {
                [key: string]: number;
            };
            /**
             * Free Count
             * @description Touches déclarées et restées sans action
             */
            free_count: number;
        };
        /**
         * LogMessage
         * @description Une entrée du journal d'exécution produit par `Reporter`.
         */
        LogMessage: {
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "success" | "error" | "warning";
            /** Message */
            message: string;
            /** Timestamp */
            timestamp: string;
        };
        /** Month */
        Month: {
            /** Index */
            index: number;
            /**
             * Name En
             * @description Nom utilisé dans la date stockée
             */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Days */
            days: number;
        };
        /**
         * SettingCheck
         * @description Un champ de configuration et le résultat de sa validation.
         */
        SettingCheck: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Required */
            required: boolean;
            /**
             * Kind
             * @description Type de chemin vérifié ; null si non vérifié
             */
            kind?: ("file" | "dir") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error" | "empty";
            /** Message */
            message: string;
        };
        /** SettingsOut */
        SettingsOut: {
            /** All Ok */
            all_ok: boolean;
            /** Checks */
            checks: components["schemas"]["SettingCheck"][];
            /**
             * Config Path
             * @description Fichier réellement écrit par PUT (voir CONFIG_ENV_PATH)
             */
            config_path: string;
        };
        /**
         * SettingsWrite
         * @description Corps de `PUT /api/v1/settings` : {clé: valeur} pour les champs connus.
         *
         *     Les clés inconnues sont ignorées — on n'écrit jamais une variable arbitraire
         *     dans le fichier de configuration depuis une requête HTTP.
         */
        SettingsWrite: {
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * SuggestedDateOut
         * @description Date proposée par défaut pour une catégorie.
         */
        SuggestedDateOut: {
            date: components["schemas"]["GameDate"];
            /**
             * Source
             * @description 'last_known' si tirée du XML de la catégorie, 'default' sinon
             */
            source: string;
            /**
             * Stored
             * @description Forme stockée correspondante
             */
            stored: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigStatusOut"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    list_arcs_api_v1_arcs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_metadata_files_api_v1_metadata_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    read_metadata_file_api_v1_metadata_files__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Fichier inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fichier illisible ou JSON invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_calendar_api_v1_calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
        };
    };
    suggest_date_api_v1_calendar_suggest_get: {
        parameters: {
            query: {
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestedDateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_injections_api_v1_injections_get: {
        parameters: {
            query?: {
                categorie?: string;
                arc?: string;
                search?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_injection_api_v1_injections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectionResultOut"];
                };
            };
            /** @description Texte déjà injecté ; rejouer avec allow_duplicate=true */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Le pipeline a échoué ; voir `messages` */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Configuration applicative invalide */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    injection_facets_api_v1_injections_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectionFacets"];
                };
            };
        };
    };
    get_injection_api_v1_injections__injection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                injection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectionDetail"];
                };
            };
            /** @description Injection inconnue */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_pdf_api_v1_injections__injection_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                injection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aucun PDF disponible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_keymap_api_v1_keymap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeymapOut"];
                };
            };
        };
    };
    set_keybind_api_v1_keybinds__scan_code__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Scan code DirectInput de la touche */
                scan_code: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyBindWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyBind"];
                };
            };
            /** @description Famille inconnue */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clear_keybind_api_v1_keybinds__scan_code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Scan code DirectInput de la touche */
                scan_code: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_keybinds_api_v1_keybinds_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
